language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get install -qq gfortran
  - pip install -r requirements.txt
install:
  - python setup.py build install
script:  py.test
